## Instructor {-}

Rick O. Gilmore, Ph.D. \
Professor of Psychology \
rog1 AT-SIGN psu PERIOD edu \

### Office hours

Monday & Friday, 12:00p - 1:00p in 114 Moore or by appointment: <https://doodle.com/mm/rickgilmore/book-a-time></br>

Lab web site: <https://gilmore-lab.github.io>

## Teaching Assistant {-}

Kalvin Garrah \
Graduate Student in Social Psychology \
kmg7035 AT-SIGN psu PERIOD edu \

### Office hours

TBD

## Meeting time & location {-}

Monday, Wednesday, & Friday, 3:35 pm - 4:25 pm \
216 [Osmond Lab](https://map.psu.edu/?id=1134#!ct/25403,26748,26749,26750,27255?m/274773?s/Osmond)

## Canvas site

Most of the course content will be found on this site.

However, we will use Canvas to track attendance, submit and grade assignments, and provide ongoing summaries about grade point totals.
The Canvas site may be found here: 

<https://psu.instructure.com/courses/2484925>

## Course structure

This is a discussion-focused course.
On most days we will discuss readings assigned prior to class.
On many days, we will work together or individually on the assigned [exercises](index.qmd#exercises), the final project, or another assignment.
Please remember to bring your personal laptop computer.
If you do not have a personal laptop, contact Dr. Gilmore so that we can make arrangements for you to participate fully in the course activities.
