project:
  type: book
  render:
    - "./*.qmd"
    - "tutorials/*.qmd"
    - "surveys/*.qmd"
    - "slides/*.qmd"
    - "exercises/*.qmd"
    - "supplemental/*.qmd"
  output-dir: "docs"
  lib-dir: site_libs

book:
  title: "PSYCH 490.007"
  author: "Rick Gilmore"
  chapters:
    - text: "Home"
      href: index.qmd
    - href: schedule.qmd
    - href: evaluation.qmd
    - href: deadlines.qmd
    - href: policies.qmd
    # - part: Exercises
    #   chapters: 
    #     # - exercises/ex01-figs-in-psych-sci.qmd
    #     # - exercises/ex02-data-viz-outside-psych.qmd
    #     # - exercises/ex03-making-data.qmd
    #     # - exercises/ex04-sci-of-data-viz.qmd
    #     # - exercises/ex05-figure-prep-guidelines.qmd
    #     # - exercises/ex06-figs-w-r.qmd
    #     # - exercises/ex07-figs-w-python.qmd
    #     # - exercises/final-project.qmd
    # - part: Tutorials
    #   chapters:
    #     - tutorials/tutorial-making-data.qmd
    #     - tutorials/tutorial-rstudio-on-pc.qmd
    #     - tutorials/tutorial-rstudio-on-psu.qmd
    #     - tutorials/tutorial-r-ggplot.qmd
    #     - tutorials/tutorial-python-matplotlib.qmd
    # - part: Supplemental
    #   chapters:
        # - href: supplemental/ex01-feedback.qmd
        # - href: supplemental/psych-sci-figs.qmd
        # - href: supplemental/other-field-figs.qmd
        # - href: supplemental/ex03-deep-dive.qmd
        # - href: supplemental/ex03-feedback.qmd
        # - href: supplemental/gestalt-in-the-wild.qmd
        # - href: supplemental/presentation-schedule.qmd
    - text: Meta
      href: meta.qmd
  repo-url: https://github.com/psu-psychology/psych-490-data-viz-2026-fall
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © Rick Gilmore • [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "Built with [Quarto](https://quarto.org/)"
    right:
      - icon: github
        href: https://github.com/rogilmore
    background: light
format:
  html:
    theme: [cosmo, include/css/psu.scss]
    number-sections: false
    citations-hover: false
    footnotes-hover: false
    crossrefs-hover: true
    link-external-icon: true
    date-modified: last-modified
    date: today
    bibliography: [include/bib/packages.bib, include/bib/data-viz.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax
    code-fold: true
    code-tools: true
    lightbox: true
    bread-crumbs: false
    reader-mode: false
editor: source

jupyter: python3

knitr:
  opts_chunk:
    fig.path: include/fig/
