---
title: "Exercise 01"
subtitle: "Data visualization in Psychological Science"
---

## Dates {-}

In-class work on Tuesday, January 14 and Thursday, January 16.

Write-up for credit [due]{.orange_due} on [Thursday, January 23](../schedule.qmd#thursday-january-16).

[Canvas dropbox](https://psu.instructure.com/courses/2381584/assignments/16998394).

::: {.callout-important}
## Post-submission feedback

We have prepared a page with general feedback that should be helpful for future assignments.
The feedback can be found [here](../supplemental/ex01-feedback.qmd).

:::

## Goals {-}

In this exercise, you may choose to work alone or with a team of no more than two other classmates to find data visualizations from the societies of three (3) professional associations and three (3) journals.
You will add links to the visualizations to a common database that we will use for discussion about the types of visualizations and types of data that are commonly used in psychological science.

## Assignment {-}

1. Visit the websites of at least three (3) professional associations.

The following are examples. Feel free to choose a different professional society.

- [American Psychological Association (APA)](https://www.apa.org)
- [Association for Psychological Science (APS)](https://www.psychologicalscience.org)
- [Vision Sciences Society](https://www.visionsciences.org)
- [Society for Personality and Social Psychology](https://spsp.org)
- [Society for Research in Child Development](https://www.srcd.org)
- [Society for Research on Adolescence](https://www.s-r-a.org)
- [Cognitive Neuroscience Society](https://www.cogneurosociety.org)
- [Society for Neuroscience](https://sfn.org)
- [Psychonomics Society](https://www.psychonomic.org)
- [Society for Industrial and Organizational Psychology](https://siop.org)

2. For each society website, find at least two visualizations of data.

Try to pick visualizations that are interesting to you in some way.

3. Add information about the visualizations to a Google Sheet that all of us will share:

<https://docs.google.com/spreadsheets/d/1X-3kWpGAACdkAJ8-AeqYiu5TS6tRzpfdgXBYyPooCPo/edit?usp=sharing>

Specifically, enter your team identifier in the `identifier` field, the source in `source_type`, and the URL in the `url` field. Please say briefly why you chose this particular visualization. If you have any comments to add, put those in the `comments` field. 

During class on 2025-01-16, Gilmore added a `url_to_figure` field. If you want to add that, right click on the image and see if an option to 'open image in new tab' or 'copy image address' is available.

::: {.callout-important}
You do **not** have to use your PSU ID as your identifier.

Gilmore did so just to provide some sample data.
:::

4. Next, visit the websites of at least three (3) journals and do the same thing--pick at least two (2) visualizations from each of the journals.

Note that some societies publish one or more journals, so you might find a journal that interests you from the society website.

Here are some additional journal resources that you might find interesting to explore:

- [Science Magazine](https://www.science.org)
- [Nature](https://www.nature.com)
- [Nature Human Behavior](https://www.nature.com/nathumbehav)
- [Trends in Cognitive Sciences](https://www.cell.com/trends/cognitive-sciences/home)
- [Annual Reviews](https://www.annualreviews.org)
  - [Figures with "psychology" as search term](https://www.annualreviews.org/search?value1=psychology&option1=fulltext&facetOptions=51&value51=%22Figure%22&facetNames=contentType_facet&option51=contentType_facet&operator51=AND)
  - [Figures with "neuroscience" as search term](https://www.annualreviews.org/search?value1=neuroscience&option1=fulltext&facetOptions=51&value51=%22Figure%22&facetNames=contentType_facet&option51=contentType_facet&operator51=AND)
  - [Knowable Magazine](https://knowablemagazine.org/) has a [graphics library](https://www.flickr.com/photos/knowablemag/)

::: {.callout-important}
The goal here is to gather via 'crowd-sourcing' a diverse set of visualizations.
So, feel free to mix it up.
:::

## Submit {-}

- Everyone
  - Your data to the shared Google Spreadsheet.
- Students who want this submission to count for one of their four (4) *required* exercises
  - A 2-3 page write-up in APA format where you describe three (3) figures your group found, focusing on these questions:
    - What graphic elements of the visualization map to which aspects of the data?
    - What prior knowledge does someone viewing these data need to have in order to understand the visualizations clearly?
    - Why is the source presenting these data?
    - What story or message is the source trying to communicate and to what audience?
    - How effective is the message?
  - Students who work in teams should submit one (1) write-up with all of the authors' names. One grade will be assigned.
  - **Note**: Your references section need only include the citation to the source paper or website. You should identify in your text which figure you have chosen to analyze.
  
::: {.callout-important}
## APA template

This [template](https://docs.google.com/document/d/1gkQKBTc7yW03VAndEtX6loWjm7BAmmhO/edit) document  may be helpful.

:::